config/routes.rb
Rails.application.routes.draw do
  resources :eleaves 
  resources :holidays 
  resources :users
  devise_for :employees

  post 'eleaves/new', to: 'eleaves#create'
  post 'eleaves/:id/edit', to: 'eleaves#update'

  post 'users/new', to: 'users#create'
  post 'users/:id/edit', to: 'users#update'

  post 'holidays/new', to: 'holidays#create'
  post 'holidays/:id/edit', to: 'holidays#update'

  get 'projectsmanagements', to: 'projects_management#projectsmanagement'

  get 'designationmanagement', to: 'designation_management#designationmanagement'
  post 'designationmanagement', to: 'designation_management#create'

  get 'leavesmanagement', to: 'leaves_management#leavesmanagement'
  post 'leavesmanagement', to: 'leaves_management#create'


  #employee urls
  get 'dashboard', to: 'dashboard#dashboard'
  get 'attendance', to: 'attendance#attendance'
  get 'leaves', to: 'leaves#leaves'
  get 'settings', to: 'settings#settings'

  get 'about', to: 'pages#home'

  root 'pages#home'
end

app/models/address.rb
class Address < ApplicationRecord
  belogns_to :employee  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
end

app/models/designation.rb
class Designation < ApplicationRecord
  has_many :employees, through: :employee_details
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :employee_detail
  has_one :addresses
  has_many :attendances
  has_many :employee_leave
  #has_many :leaves, :through=> :employee_leaves
  has_one :designation, :through=> :employee_detail
  has_many :employee_projects
  has_and_belongs_to_many :employee_projects
  belongs_to :role
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
  belongs_to :employee 
  belongs_to :designation 
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
  belongs_to :employee
  has_one :leave
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
  belongs_to :project 
  belongs_to :employee 
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
  has_many :employee_leaves
end

app/models/project.rb
class Project < ApplicationRecord
  # has_many: employees
  #has_many :employee_projects
  #has_many :employees, :through=> :employee_projects
  has_and_belongs_to_many :employees
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :employees
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:edit, :update, :destroy]

  def index
    @holidays = Holiday.all
  end

  def new
    @holiday = Holiday.new
  end

  def edit 
  end

  def create 
    @holiday = Holiday.new(holidays_params)
    if @holiday.save 
      redirect_to holidays_path
    else  
      render 'new'
    end
  end

  def update 
    if @holiday.update(holidays_params)
      redirect_to holidays_path
    else  
      render 'edit'
    end
  end

  def destroy 
    @holiday.destroy 
    redirect_to holidays_path
  end

  private 

  def holidays_params 
    params.permit(:name, :date, :year)
  end

  def set_holiday 
    @holiday = Holiday.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/zensark_helper.rb
module ZensarkHelper
end

app/views/holidays/_form.html.erb
<%= form_with model:@holidays do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_field :date, autofocus: true, autocomplete: "description" %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<div class="designation-main-container">
  <%= render 'layouts/adminleftnav' %>
  <div class="employee-management-right-container">
    <h1 class="employees-management-heading">Holidays Management</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/holidays/index.html.erb
<div class="designation-main-container">
  <%= render 'layouts/adminleftnav' %>
  <div class="employee-management-right-container">
    <h1 class="employees-management-heading">Holidays Management</h1>
    <div class="employee-management-search-container">
      <%= link_to "Add New Holiday", new_holiday_path,  class: "btn employee-management-add-employee-button" %>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search Holiday" aria-label="Search">
        <button class="btn employee-management-search-button" type="submit">Search</button>
      </form>
    </div>
    <div>
      <table class="table-container">
        <tr class="t-header-cotainer">
            <th>Holiday Name</th>
            <th>Holiday Date</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <% @holidays.each do |holiday| %>
            <tr class="t-sub-container">
                <td>
                <%= holiday.name %>
                </td>
                <td>
                <%= holiday.date %>
                </td>
                <td>
                <%= link_to "Edit", edit_holiday_path(holiday), class: "btn btn-primary" %> 
                </td>   
                <td>
                <%= button_to "Delete", holiday_path(holiday),  class: "btn btn-danger", method: :delete %>
                </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/holidays/new.html.erb
<div class="designation-main-container">
  <%= render 'layouts/adminleftnav' %>
  <div class="employee-management-right-container">
    <h1 class="employees-management-heading">Holidays Management</h1>
    <%= render 'form' %>
  </div>
</div>